// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK_wSkQuL4bGVBgYIwNwTNNNXnX_c6OfM',
    appId: '1:222644778930:web:d43dbd8ef9f8245dd6d6ab',
    messagingSenderId: '222644778930',
    projectId: 'bmifirebase-3c3ba',
    authDomain: 'bmifirebase-3c3ba.firebaseapp.com',
    storageBucket: 'bmifirebase-3c3ba.appspot.com',
    measurementId: 'G-08181XV09S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOyCWzu1ePKaccQj9aBkv38V6n3C_YlLw',
    appId: '1:222644778930:android:6ef874be8683306bd6d6ab',
    messagingSenderId: '222644778930',
    projectId: 'bmifirebase-3c3ba',
    storageBucket: 'bmifirebase-3c3ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkuEvAvOXT1Y_mDKhEKVtSdYXijo5udNI',
    appId: '1:222644778930:ios:244b07d7c063f477d6d6ab',
    messagingSenderId: '222644778930',
    projectId: 'bmifirebase-3c3ba',
    storageBucket: 'bmifirebase-3c3ba.appspot.com',
    iosClientId: '222644778930-sjo4jbefn4d9u0d3sh9nnjvh80lq9k21.apps.googleusercontent.com',
    iosBundleId: 'com.example.bmiFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkuEvAvOXT1Y_mDKhEKVtSdYXijo5udNI',
    appId: '1:222644778930:ios:244b07d7c063f477d6d6ab',
    messagingSenderId: '222644778930',
    projectId: 'bmifirebase-3c3ba',
    storageBucket: 'bmifirebase-3c3ba.appspot.com',
    iosClientId: '222644778930-sjo4jbefn4d9u0d3sh9nnjvh80lq9k21.apps.googleusercontent.com',
    iosBundleId: 'com.example.bmiFirebase',
  );
}
